// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.example.grpclib;

public interface UserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hobe.UserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
